# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "pt-BR"
encoding: "utf-8"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: neon

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
    # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

title: Sou o Wendy
title_separator: "|"
subtitle: Um blog simples de programação

name: &name Wenderson Santos
email: ssantos.wendy42@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aqui você encontrará artigos sobre minhas
  incríveis aventuras no mundo da computação.

baseurl: "" # the subpath of your site, e.g. /blog
domain: souowendy.github.io
url: https://souowendy.github.io # the base hostname & protocol for your site, e.g. http://example.com

teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"

author:
  name: *name
  avatar: #
  bio: Just keep swimming...
  location: Brasília, BR
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/SouOWendy
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/SouOWendy
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://linkedin.com/in/wsoares-

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/SouOWendy
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/SouOWendy
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://linkedin.com/in/wsoares-
  
permalink: /:title/
timezone: America/Sao_Paulo

include:
  - "_pages"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
